#!/bin/bash
touch \*\\'"Best School"\'\\*$\?\*\*\*\*\*:)
echo Best School"[D[D[D[D[D[D[D[D[D[D[D[D"Best School" > ''[D\*\\'"Best School"\'\\*$\?\*\*\*\*\*:)
echo >> ''[D\*\\'"Best School"\'\\*$\?\*\*\*\*\*:)
